### ISSUE TITLE
Empty hologram lines with just formatting codes is inputting the name 'Armor Stand'.

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#1048]
Paper dev 597 (Spigot 1.13.2)
Travertine dev 91 (Waterfall/BungeeCord)
ProtocolSupport dev 370
HolographicDisplays dev 60

Hologram configuration.
```
spawncreative:
  location: spawn, -28.500, 55.700, 19.500
  lines:
  - '&6&lCreative Plots'
  - '&f'
  - '&f&l» &r&bPortal &f&l«'
```

On 1.13, the hologram displays fine.
![link](https://i.imgur.com/7JXmJm8.png)

On 1.12, the hologram's 2nd line (which should be empty) displays as ``Armor Stand``.
![link2](https://i.imgur.com/4hnNInn.png)
