### ISSUE TITLE
Mapping of 

### ISSUE THREAD

**Issue by zeronerve** [ProtocolSupport/ProtocolSupport#1211]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
* Server version

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by zeronerve** [comment]
![slab-issue](https://user-images.githubusercontent.com/34899120/73611514-25d8aa00-45a8-11ea-96ca-ad93a3e37f6c.jpg)

**Comment by Shevchik** [comment]
You can configure the mapping yourself using a plugin that uses protocolsupport api, such as protocolsupportstuff. Changing default mappings is always a low priority task for us, so unless somebody PRs changes to ProtocolSupportResourcesGenerator, this change won't be done.

**Comment by zeronerve** [comment]
Thanks for the quick reply!

**Comment by zeronerve** [comment]
I added this to the ProtocolSupportStuff config and everything looks great, thanks!. ....

```
blocks:
- from-state: minecraft:smooth_stone_slab[type=top]
  to-state: minecraft:stone_slab[type=top]
  before: MINECRAFT_1_12_2
- from-state: minecraft:smooth_stone_slab[type=bottom]
  to-state: minecraft:stone_slab[type=bottom]
  before: MINECRAFT_1_12_2
- from-state: minecraft:smooth_stone_slab[type=double]
  to-state: minecraft:stone_slab[type=double]
  before: MINECRAFT_1_12_2
```

No more cobblestone slabs.
